### ISSUE TITLE
Update GitHub Workflows

### ISSUE THREAD

**Issue by CedricAnover** [CedricAnover/marsh#21]
## Description
Update GitHub Workflows.

**TODO:**

- [x] Add `mikepenz/release-changelog-builder-action@v5` for changelog build in release workflow.
- [x] Reference changelog build in release creation step.
- [x] Rename release workflow to "**_Release_**".
- [x] Update PyPI Publish Workflow trigger.
  ```yaml
  on:
    workflow_run:
      workflows:
        - Release
      types:
        - completed
  ```

## Additional information
...
